### ISSUE TITLE
Exception thrown on first use

### ISSUE THREAD

**Issue by amarouni** [paul-nechifor/ohmu#26]
14:05 $ ohmu 
Traceback (most recent call last):
                                    File "/usr/local/bin/ohmu", line 9, in <module>
                                                                                       load_entry_point('ohmu==0.4.0', 'console_scripts', 'ohmu')()
                                                                                                                                                     File "/usr/local/lib/python2.7/dist-packages/ohmu/__init__.py", line 62, in entry_point
                                                  main('__main__', sys.argv[1:])
                                                                                  File "/usr/local/lib/python2.7/dist-packages/ohmu/__init__.py", line 58, in main
                                                                                                                                                                      Ohmu(root_path).start()
                                                                                                                                                                                               File "/usr/local/lib/python2.7/dist-packages/ohmu/__init__.py", line 24, in start
                                                                                      self.screen.start()
                                                                                                           File "/usr/local/lib/python2.7/dist-packages/ohmu/views.py", line 177, in start
                                                                                                                                                                                              curses.init_pair(i + 1, 15, color)
                                  _curses.error: init_pair() returned ERR

Weird formatting of the exception.

For info : xubuntu 14.04
I use my own TERM.

**Comment by davertron** [comment]
I'm seeing this as well on OSX Yosemite. Using python 2.7.9.

Just for clarification, this happens every time I try to run it, not just the first time.

**Comment by mozai** [comment]
Seeing it here; Ubuntu 15.04, Python 2.7.9

**Comment by Tobias1087** [comment]
I think this is down to your TERM being not detected by curses as 256 colours and defaults to 8. I got it to work on OSX Yosemite, in iTerm2 when running with:

    env TERM=xterm-256color ohmu

I assume this only works if your terminal does actually support 256 colours.  iTerm2 for me just reports TERM as xterm-color

**Comment by davertron** [comment]
That does seem to be the problem. I was executing it inside tmux, where
$TERM=screen, but in normal iterm2 it's xterm-256color and works fine.

**Comment by fiatjaf** [comment]
seeing it here, the problem is that it is unformatted: 

```
fiatjaf@spooner ~> ohmu
Traceback (most recent call last):
                                    File "/usr/local/bin/ohmu", line 9, in <module>
                                                                                       load_entry_point('ohmu==0.4.0', 'console_scripts', 'ohmu')()
                                                                                                                                                     File "/usr/local/lib/python2.7/dist-packages/ohmu/__init__.py", line 62, in entry_point
                                                            main('__main__', sys.argv[1:])
                                                                                            File "/usr/local/lib/python2.7/dist-packages/ohmu/__init__.py", line 58, in main
                                                                                                                                                                                Ohmu(root_path).start()
                     File "/usr/local/lib/python2.7/dist-packages/ohmu/__init__.py", line 24, in start
                                                                                                          self.screen.start()
                                                                                                                               File "/usr/local/lib/python2.7/dist-packages/ohmu/views.py", line 177, in start
                              curses.init_pair(i + 1, 15, color)
                                                                _curses.error: init_pair() returned ERR
                                                                                                       ⏎                                                                            fiatjaf@spooner ~> 
```

**Comment by fiatjaf** [comment]
but yes, `env TERM=xterm-256color ohmu` solves it.

this is strange, because I use vim with a 256 color setup.

**Comment by dellis23** [comment]
What's the best solution?  I'm assuming curses is trying to detect whether the colors are supported before using them, but the terminals aren't setting the value it's using properly first?  I wonder how vim checks or if it just makes the assumption that all colors are available.

**Comment by fiatjaf** [comment]
I was supposing I had set this somehow somewhere, but couldn't find any trace of it neither in my .vimrc nor in my .bashrc.

Maybe ohmu could set this environment variable in its start? I don't know.

**Comment by dellis23** [comment]
Okay, I believe I have figured this one out.  Can someone else give it a shot?

**Comment by paul-nechifor** [comment]
Yep, works with `TERM=screen ohmu` (it didn't before).

Thanks very much @dellis23 ! I probably would never have figured that out.
