### ISSUE TITLE
OverflowError: byte doesn't fit in chtype

### ISSUE THREAD

**Issue by jojomi** [paul-nechifor/ohmu#31]
```$ ohmu
Traceback (most recent call last):
  File "/usr/bin/ohmu", line 9, in <module>
    load_entry_point('ohmu==0.4.3', 'console_scripts', 'ohmu')()
  File "/usr/lib/python3.5/site-packages/ohmu/__init__.py", line 62, in entry_point
    main('__main__', sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/ohmu/__init__.py", line 58, in main
    Ohmu(root_path).start()
  File "/usr/lib/python3.5/site-packages/ohmu/__init__.py", line 25, in start
    self.loop()
  File "/usr/lib/python3.5/site-packages/ohmu/__init__.py", line 45, in loop
    self.screen.tick(now, self.scanner)
  File "/usr/lib/python3.5/site-packages/ohmu/views.py", line 198, in tick
    self.screen.insch(i, j, char, curses.color_pair(1 + color) | curses.A_BOLD)
OverflowError: byte doesn't fit in chtype
```
Happens after some scanning. I would assume it might be connected to unicode in folder names?

**Comment by fpietka** [comment]
👍  same here

**Comment by paul-nechifor** [comment]
Hi, @jojomi and @fpietka. I know this is an offensively long time to wait for a reply, but do you have any more details about this bug like what OS you're using and what filename it fails for?

**Comment by fpietka** [comment]
I'm on OSX. As for the filename I don't remember catching it.
I can try to reproduce.

**Comment by paul-nechifor** [comment]
I've never used OSX. I don't know how to debug this. :(

**Comment by fpietka** [comment]
Corresponding `i`, `j`, `char` and `color` from where it fail:
```
27
124
华
0
```

**Comment by fpietka** [comment]
ok, so way to reproduce:
```
mkdir /tmp/ohmu_test && cd /tmp/ohmu_test
touch 华
ohmu
```

**Comment by fpietka** [comment]
Fail with `touch é` too, so it seems related to wide character. That's all I got for now.

**Comment by fpietka** [comment]
Ok, found that it fails only with python 3, not with python 2

**Comment by paul-nechifor** [comment]
Yep, I can reproduce this with Python 3 on Ubuntu. Thanks!
